spring:
  application:
    name: springboot_filter_teams
  datasource:
    url: jdbc:mysql://localhost:3307/filter_meta_db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: d3b1b9e7a9f4e0
    password: 447203787dce1c
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

